apiVersion: v1
kind: Pod 
metadata:
  name: ipl-pod 
  namespace: ipl-ns
spec:
  containers:
    - name: ipl 
      image: muralisocial123/ipl:latest
      ports:
        - containerPort: 3000

    - name: netflix 
      image: muralisocial123/netflix:latest
      ports:
        - containerPort: 80 