apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: ipl-rs
  namespace: ipl-ns
spec:
  replicas: 5
  selector:
    matchLabels:
      app: ipl
  template:
    metadata:
      labels:
        app: ipl
    spec:
      containers:
        - name: ipl-container
          image: muralisocial123/ipl:latest-v2
          ports:
            - containerPort: 3000